#!/usr/bin/env python3
"""
Bridge: daban-picker → Codex manual analysis.

Reads scan_results.json (generated by daban_scanner.py --ci) and outputs
structured data for Codex to analyze.

Usage:
  python codex_analyze.py                    # summary of all candidates
  python codex_analyze.py CODE               # detail for a single stock
  python codex_analyze.py --summary          # one-line per stock
  python codex_analyze.py --near-miss        # show near-miss list
"""
import json
import os
import sys

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
SCAN_FILE = os.path.join(SCRIPT_DIR, "scan_results.json")


def load():
    if not os.path.exists(SCAN_FILE):
        print(f"ERROR: {SCAN_FILE} not found. Run daban_scanner.py --ci first.")
        sys.exit(1)
    with open(SCAN_FILE, encoding="utf-8") as f:
        return json.load(f)


def print_summary(data):
    """Compact one-line per stock."""
    print(f"=== {data['date']} | {data['total_limit_ups']}涨停 → {data['stages']['candidates']}候选 ===")
    if data.get("hot_sectors"):
        hot = ", ".join(f"{h['sector']}({h['count']})" for h in data["hot_sectors"])
        print(f"热点: {hot}")
    print()

    candidates = data.get("candidates", [])
    if not candidates:
        print("😔 无打板候选标的。")
        return

    for c in candidates:
        print(f"{c['code']} {c['name']:8s} ¥{c['price']:<8} "
              f"{c['change_pct']:+.2f}%  "
              f"封板{c['first_seal_time']} "
              f"封单{c['seal_amount_str']:>6s} "
              f"换手{c['turnover']:.1f}% "
              f"市值{c['float_mcap_str']} "
              f"板块:{c['sector']}")


def print_detail(item):
    """Full detail for a single stock."""
    print(f"=== {item['code']} {item['name']} ===")
    print(f"价格: ¥{item['price']} ({item['change_pct']:+.2f}%)")
    print(f"首次封板: {item['first_seal_time']}")
    print(f"封板资金: {item['seal_amount_str']}")
    print(f"连板数: {item['board_num']}")
    print()
    print(f"换手率: {item['turnover']:.2f}%")
    print(f"流通市值: {item['float_mcap_str']}")
    print(f"成交额: {item['volume_str']}")
    print(f"所属行业: {item['sector']} {'🔥热点' if item.get('is_hot_sector') else ''}")
    print(f"涨停统计: {item.get('board_stat', '?')}")


def print_near_miss(data):
    """Show near-miss list."""
    near = data.get("near_miss", [])
    if not near:
        print("无近失数据。运行扫描时请使用 --near-miss 模式。")
        return

    print(f"=== 近失名单 ({len(near)} 只，差 1-2 个条件) ===")
    print()
    for i, nm in enumerate(near[:20]):
        print(f"{i+1:2d}. {nm['code']} {nm['name']:8s} ¥{nm['price']:<8} "
              f"{nm['change_pct']:+.2f}%  "
              f"封板{nm['first_seal_time']} "
              f"封单{nm['seal_amount_str']:>6s} "
              f"换手{nm['turnover']:.1f}% "
              f"市值{nm['float_mcap_str']}")
        print(f"    板块: {nm['sector']} | 未通过: {', '.join(nm['failed_rules'])}")


def main():
    data = load()

    if "--summary" in sys.argv:
        print_summary(data)
        return

    if "--near-miss" in sys.argv:
        print_near_miss(data)
        return

    # Check for stock code argument
    code = None
    for arg in sys.argv[1:]:
        if not arg.startswith("--") and len(arg) == 6 and arg.isdigit():
            code = arg
            break

    if code:
        item = next((c for c in data.get("candidates", []) if c["code"] == code), None)
        if item:
            print_detail(item)
        else:
            # Check near-miss
            item = next((n for n in data.get("near_miss", []) if n["code"] == code), None)
            if item:
                print(f"=== {item['code']} {item['name']} (近失) ===")
                print(f"价格: ¥{item['price']} ({item['change_pct']:+.2f}%)")
                print(f"封板: {item['first_seal_time']} | 封单: {item['seal_amount_str']}")
                print(f"市值: {item['float_mcap_str']} | 板块: {item['sector']}")
                print(f"未通过条件: {', '.join(item['failed_rules'])}")
            else:
                print(f"Stock {code} not found in today's scan.")
    else:
        print_summary(data)
        # Also show near-miss count if available
        near = data.get("near_miss", [])
        if near:
            print(f"\n近失: {len(near)} 只 (python codex_analyze.py --near-miss 查看详情)")
        print()


if __name__ == "__main__":
    main()
